# Copyright (C) 2020 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/oneplus/opcamera/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    device/oneplus/opcamera

PRODUCT_COPY_FILES += \
    device/oneplus/opcamera/proprietary/lib/libCameraMDMHelper.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libCameraMDMHelper.so \
    device/oneplus/opcamera/proprietary/lib/libopcameralib-em.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libopcameralib-em.so \
    device/oneplus/opcamera/proprietary/lib/vendor.oneplus.hardware.CameraMDMHIDL@1.0-adapter-helper.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vendor.oneplus.hardware.CameraMDMHIDL@1.0-adapter-helper.so \
    device/oneplus/opcamera/proprietary/lib/vendor.oneplus.hardware.CameraMDMHIDL@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vendor.oneplus.hardware.CameraMDMHIDL@1.0.so \
    device/oneplus/opcamera/proprietary/lib/vendor.oneplus.hardware.camera@1.0-adapter-helper.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vendor.oneplus.hardware.camera@1.0-adapter-helper.so \
    device/oneplus/opcamera/proprietary/lib/vendor.oneplus.hardware.camera@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vendor.oneplus.hardware.camera@1.0.so \
    device/oneplus/opcamera/proprietary/lib64/libCameraMDMHelper.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libCameraMDMHelper.so \
    device/oneplus/opcamera/proprietary/lib64/libopcameralib-em.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libopcameralib-em.so \
    device/oneplus/opcamera/proprietary/lib64/vendor.oneplus.hardware.CameraMDMHIDL@1.0-adapter-helper.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vendor.oneplus.hardware.CameraMDMHIDL@1.0-adapter-helper.so \
    device/oneplus/opcamera/proprietary/lib64/vendor.oneplus.hardware.CameraMDMHIDL@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vendor.oneplus.hardware.CameraMDMHIDL@1.0.so \
    device/oneplus/opcamera/proprietary/lib64/vendor.oneplus.hardware.camera@1.0-adapter-helper.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vendor.oneplus.hardware.camera@1.0-adapter-helper.so \
    device/oneplus/opcamera/proprietary/lib64/vendor.oneplus.hardware.camera@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vendor.oneplus.hardware.camera@1.0.so \
    device/oneplus/opcamera/proprietary/product/lib/libseccam-ipc.so:$(TARGET_COPY_OUT_PRODUCT)/lib/libseccam-ipc.so \
    device/oneplus/opcamera/proprietary/product/lib/libseccam.so:$(TARGET_COPY_OUT_PRODUCT)/lib/libseccam.so \
    device/oneplus/opcamera/proprietary/product/lib/libseccamservice.so:$(TARGET_COPY_OUT_PRODUCT)/lib/libseccamservice.so \
    device/oneplus/opcamera/proprietary/product/lib/vendor.qti.hardware.seccam@1.0.so:$(TARGET_COPY_OUT_PRODUCT)/lib/vendor.qti.hardware.seccam@1.0.so \
    device/oneplus/opcamera/proprietary/product/lib64/libseccam-ipc.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/libseccam-ipc.so \
    device/oneplus/opcamera/proprietary/product/lib64/libseccam.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/libseccam.so \
    device/oneplus/opcamera/proprietary/product/lib64/libseccamservice.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/libseccamservice.so \
    device/oneplus/opcamera/proprietary/product/lib64/vendor.qti.hardware.seccam@1.0.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/vendor.qti.hardware.seccam@1.0.so

PRODUCT_PACKAGES += \
    CameraPicProcService \
    OnePlusCameraService \
    oneplus-framework-res \
    seccamservice \
    vendor.oneplus.hardware.CameraMDMHIDL-V1.0-java \
    vendor.oneplus.hardware.camera-V1.0-java
